### ISSUE TITLE
'cp a.txt b.txt' fails on Windows

### ISSUE THREAD

**Issue by kal247** [briandfoy/PerlPowerTools#115]
On Windows, `cp a.txt b.txt` fails at line 252 with message "cp: can not access B.TXT ... skipping".

Overall, this script has problems with case sensitivity, for example `cp a.txt dir` will create `dir/A.TXT`.

**Comment by briandfoy** [comment]
Okay, noted. 

I agree that many of the scripts have problems, but I also remember that they were often written in the previous millennium.

If someone wants to wholly replace it with something that works (using only core modules), I can merge that patch.
