### ISSUE TITLE
script "units" generates error messages even before asking for input

### ISSUE THREAD

**Issue by jgpuckering** [briandfoy/PerlPowerTools#162]
_I submitted this recently to RT Bug Tracker (see ticket 148683) not noticing the "Preferred bug tracker" heading.  So I'm resubmitting it here._

---------------------------

The units utility contains a table of unit definitions in the DATA section that includes temperature units.  Unfortunately the formulae for these units include subtraction, and subtraction is not supported by the units parser.  Moreover, some definitions are incomplete (lacking a scaling factor).

Here's what you get when you run the version of units included in PPT 1.034:

Show quoted text

```
Parse error: Syntax error.  Skipping.
Parse error: Unknown unit `F'.  Skipping.
Parse error: Syntax error.  Skipping.
Parse error: Unknown unit `C'.  Skipping.
Parse error: Unknown unit `degC'.  Skipping.
Parse error: Unknown unit `kelvin'.  Skipping.
Parse error: Unknown unit `degC'.  Skipping.
```

I took a run at fixing this by trying to extend the parser to include affine conversions, but after several attempts I gave up on that approach.  

One obstacle I ran into is that the current logic relies a great deal on using unity ("1") as the identity operand during reductions.  That doesn't work with affine transformations like temperature, which need scaling (multiplication and division) as well as translation (addition and subtraction).  Fixing it seemed to involve a lot of code rework, including adding at least two more state transitions to a parser that is a struggle to understand with twelve.  (Well, for me anyway!)  And with no test script in the distribution the risk of regression seemed too high.

Another obstacle is that the output is displayed as a multiplication factor and a division factor -- thus presuming all conversions involve linear scaling.  If I ask to convert "cm" to "in" I get * 0.393701 and / 2.54.  If I change that to "100 cm", I get * 39.3701 and / 0.0254.  But if I'm converting 100 degrees Celsius to Fahrenheit, I want to see a result of 212 F, not scaling factors that only make sense for a specific temperature quantity.   Moreover, the default quantity is 1, whereas 0 is more sensible for temperature.  And if you enter a zero multiplier (e.g. "0 K") you get a PARSE_ERROR.

To address these and other issues I enhanced the code to allow unit definitions to consist of a pair of from/to functions, for conversion between the unit and its dimensional base unit.  These are eval'd, thus allowing future extensions of this sort.  I also enhanced the script to allow a non-interactive mode wherein the have and wanted units are passed as command-line arguments, and I added a test() function which returns results as a hash (rather than printing to stdout).  This changes made it easier to write a test script, which I also did.

I also made some changes to the DATA section, mainly related to the temperature units.  These weren't working anyway so I figured upward compatibility wasn't an issue.  One other change I made was to comment out the entry for the "k" unit, which is defined as 1.38047e-16 erg/degC.  That looks similar to the Boltzman constant, but if that's what it is supposed to be then it is incorrect.  I didn't bother to correct it because I wasn't sure, and in any event it involves a mix of affine and linear dimensions that are not supported by the script -- even with my latest changes.  Fortunately, this was the only such case in the DATA section.

I've attached a copy of units with my changes as well as the test script.  
[units_temperature_support_and_test_script.zip](https://github.com/briandfoy/PerlPowerTools/files/11748273/units_temperature_support_and_test_script.zip)

As this is a fairly significant change, I'm asking (per the Contributing instructions) whether I should contribute these changes to the project.

**Comment by briandfoy** [comment]
Yes, you should contribute. You can either make a pull request yourself or I will take the work in the zip file and do it on your behalf. Thanks,

**Comment by jgpuckering** [comment]
Thanks for the quick reply.  Ok, I'll take a whack at it.  I've been using perl for year and am retired now with time on my hands.  It's long past time for me to contribute to the community.  If all goes well on this one, I'll look into the other outstanding issues.
    On Wednesday, June 14, 2023 at 01:38:01 p.m. EDT, brian d foy ***@***.***> wrote:  
 
 


Yes, you should contribute. You can either make a pull request yourself or I will take the work in the zip file and do it on your behalf. Thanks,

**Comment by jgpuckering** [comment]
Brian, I used git locally all the time, and have a couple of CPAN projects on GitHub.  But I'm still a novice working with remote repositories.  That said, I'm eager to learn.  I just not sure of the process to get started with this project.
I have the GitHub Windows desktop, though I don't use it much.  Mostly I use TortoiseGit.  
I cloned the repo locally and I then did a Pull request.  I noticed that the log shows that work done previously on ed by Michael Mikonos was done on a branch.  So I'm thinking I should create a branch for this change, make the changes, and then push them.  Then you can decided whether and when to merge them.
Have I got that right?  Am I missing any steps?
    On Wednesday, June 14, 2023 at 01:38:01 p.m. EDT, brian d foy ***@***.***> wrote:  
 
 


Yes, you should contribute. You can either make a pull request yourself or I will take the work in the zip file and do it on your behalf. Thanks,

**Comment by briandfoy** [comment]
You can fork this repository and work in the master branch of your fork. When you push to your forked repo then look at its page on GitHub, there should be an info box at the top that prompts you to make a pull request. Just follow the steps. If something goes goofy it's not a big deal. I think [How to create a pull request in GitHub](https://opensource.com/article/19/7/create-pull-request-github) is a decent walk-through, although it's a bit over-detailed in places.

Michael was working in branches mostly because he has several things he's pushing at the repo at one time. You can work in a branch if you like, but it doesn't bother me if you don't.

**Comment by jgpuckering** [comment]
Scratch my previous statement.  I’ll be forking the repo and doing a pull request.
________________________________

**Comment by briandfoy** [comment]
No problem. Your plan sounds fine.
