### ISSUE TITLE
bc: test binary assignment

### ISSUE THREAD

**Issue by jgpuckering** [briandfoy/PerlPowerTools#169]
Test coverage should be augmented to include:

- [ ] operators *= /= %= ^=
- [ ] scale, ibase and obase variables and their effects
- [ ] "define FUNCTION", which doesn't work and so the test should be wrapped in a TODO block
- [ ] the -b option (which used Math::BigFloat)
- [ ] the if statement

**Comment by briandfoy** [comment]
I've split out the issues so we can handle them one at a time so unrelated issues don't hold up this issue, which is now about binary assignment.

* scale, ibase and obase (#171)
* define (#172)
* -b (#173)
* if (#174)

**Comment by briandfoy** [comment]
I have a few tests in 6a2885452a29d1386dc3946c4cde50dda1c50a38, but I also need to test the bad case. These output warnings so I have to figure out what to do with those.

**Comment by briandfoy** [comment]
There are some todo tests, but the cases I can imagine have tests.
