### ISSUE TITLE
shebang should pass by env

### ISSUE THREAD

**Issue by mjbright** [briandfoy/PerlPowerTools#18]
Is there some reason against using
    #!/usr/bin/env perl
instead of
    #!/usr/bin/perl
?

Using env seems like a better option to me.

**Comment by briandfoy** [comment]
Using env finds the first perl in your path, which might not be a suitable
perl for what you installed and may not have the right dependencies
installed.

**Comment by dtikhonov** [comment]
> Using env finds the first perl in your path

This is exactly how `plenv` works...
