### ISSUE TITLE
Do not install executables by default?

### ISSUE THREAD

**Issue by miyagawa** [briandfoy/PerlPowerTools#19]
On many systems, if you accidentally install PerlPowerTools many of the tools get broken.

https://github.com/tokuhirom/plenv/issues/78
https://github.com/miyagawa/cpanminus/issues/443#issuecomment-93741302

While I love the idea of replicating UNIX tools written in pure perl, it sounds a bit too easy to accidentally break the system. Could you consider not install these executables by default without some options such as `--install-executables` are passed to configure script Makefile.PL?

**Comment by briandfoy** [comment]
Well, the point of Perl Power Tools is to install the executables. We'll have to come up with something to work around, this though, and lots of warnings in the docs.

I think perhaps they should be installed into a directory that is not in PATH and that people should have to add that new path to PATH themselves, and at the end of PATH.

**Comment by miyagawa** [comment]
> I think perhaps they should be installed into a directory that is not in PATH and that people should have to add that new path to PATH themselves, and at the end of PATH.

Yeah that'd work for me as well. Thank you for considering the request!

**Comment by briandfoy** [comment]
In 1.005, I set INSTALL_BASE for the user and prompt them to set it themselves if they want something else. This should be good enough for the moment.
