### ISSUE TITLE
Failed test 'blib/script/robots compiles'

### ISSUE THREAD

**Issue by eserte** [briandfoy/PerlPowerTools#210]
t/compile.t fails with perl 5.38.0:
```
    #   Failed test 'blib/script/robots compiles'
    #   at t/compile.t line 22.
    #                   'blib/script/robots requires the Perl Curses module!
    # '
    #     doesn't match '(?^:syntax OK)'
    # Looks like you failed 1 test of 1.

#   Failed test 'blib/script/robots'
#   at t/compile.t line 33.
# Looks like you failed 1 test of 120.
t/compile.t ... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/120 subtests 
	(3 TODO tests unexpectedly succeeded)
```

**Comment by briandfoy** [comment]
Are there any more details on this, like a CPAN Testers report? I thought I had fixed this problem awhile ago.

**Comment by briandfoy** [comment]
Ah, I see all the failures in CPAN Testers now. I guess the new Perl installations haven't caught up on modules. 

There is a fix in the repo and I simply haven't caught up on releases since we have been moving too fast. I'll try to get to it next week.

**Comment by briandfoy** [comment]
The latest CPAN tester reports do not show this. Instead, we have a new issue that's not this. :)

Thanks for the quick heads up on the failure.
