### ISSUE TITLE
install fails for symbolic -m argument

### ISSUE THREAD

**Issue by mknos** [briandfoy/PerlPowerTools#233]
* The POD text says "Either octal modes or symbolic modes are acceptable"
* Octal mode is accepted, e.g. perl install -D -m 700 file dir
* Symbolic mode fails with missing library error

perl install -D -m u=rwx file dir
Can't locate SymbolicMode.pm in @INC (you may need to install the SymbolicMode module) (@INC contains: /usr/local/lib/perl5/site_perl/5.34.1/armv7l-linux /usr/local/lib/perl5/site_perl/5.34.1 /usr/local/lib/perl5/5.34.1/armv7l-linux /usr/local/lib/perl5/5.34.1) at install line 199.

**Comment by mknos** [comment]
Two other commands reference SymbolicMode:
1. perl mkdir -m u=rwx newdir
2. perl chmod u=rwx file

**Comment by briandfoy** [comment]
Good find. I will investigate.

**Comment by briandfoy** [comment]
I found a reference to http://www.perl.com/language/ppt/src/chmod/SymbolicMode.pm, which apparently is not in archive.org.

**Comment by briandfoy** [comment]
Found it in BackPAN (./authors/id/C/CW/CWEST/ppt-0.13.tar.gz)
[SymbolicMode.pm.txt](https://github.com/briandfoy/PerlPowerTools/files/12563018/SymbolicMode.pm.txt)

**Comment by briandfoy** [comment]
Fixed by #237
