### ISSUE TITLE
Is there an installation problem with Windows (especially Curses)

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/PerlPowerTools#27]
From Mithun Radhakrishnan <rkmithuns@gmail.com>

Hi Brian,

Just out of curiosity to use the Linux commands in win environment, I tried to install PerlPowerTools on my windows box using cpanm. Currently am using Dwimperl and perl version is (v5.14.2). 

It failed to install with below warnings.  So I installed  "App::a2p", "MIME::Parser" manually using cpanm tool. But Curses fails to install. Does this tool work on windows? 

Also attached the build.log file.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Configuring PerlPowerTools-1.006
Running Makefile.PL
Warning: prerequisite App::a2p 0 not found.
Warning: prerequisite Curses 0 not found.
Warning: prerequisite MIME::Parser 0 not found.
Warning: prerequisite Make 0 not found.
The getpwuid function is unimplemented at C:/Dwimperl/perl/site/lib/ExtUtils/MakeMaker.pm line 958.
----------------------------------------------------------------------
Welcome to Perl Power Tools (http://www.perlpowertools.com).

You didn't specify INSTALL_BASE, so I chose ~/perlpowertools.
You'll need to add this to PATH to be able to use them.

If you want to install them somewhere else, run Makefile.PL again
with your installation location:

    perl Makefile.PL INSTALL_BASE=/where/you/want/them/to/go

Most Perl distributions don't do this for you, but I'm doing this
because some of these tools installed in the wrong places can hide
the real tools, which might cause problems. I'm being careful for
you!
----------------------------------------------------------------------
Checking if your kit is complete...
Looks good
-> N/A
-> FAIL Configure failed for PerlPowerTools-1.006. See C:\Users\miradhak\.cpanm\work\1429613165.13448\build.log for details.
Expiring 4 work directories.
1 distribution installed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Other strange thing that I noticed  is even though below lines are in Makefile.PL, cpanm failed to install them automatically.

'PREREQ_PM'     => {
		'App::a2p'     => '0',
		'Make'         => '0',
		'MIME::Parser' => '0',
		'Curses'       => '0',
		'DB_File'      => '0',
		},

Cheers,
Mithun
Attachments area

**Comment by klp2** [comment]
This isn't curses related, but in 2113de17aef20cfdfa60c233aa52c43ccb558eb3 INSTALL_BASE was given a default of '~/perlpowertools'. That ultimately triggers EU::MM to run a 'getpwuid', which fails on Windows, and no Makefile is built. I'm not yet sure what the right way to find a home directory on windows is (outside of using File::Homedir).

**Comment by briandfoy** [comment]
Can you rebase off master and submit a pull request?

**Comment by klp2** [comment]
Thanks, should be set now.
