### ISSUE TITLE
units uses wrong path separator on Windows

### ISSUE THREAD

**Issue by nanis** [briandfoy/PerlPowerTools#44]
`units` consults `$ENV{UNITTAB}` for a list of conversion files. Unfortunately, it uses the hard-coded Unix style path separator `:` when splitting the contents of this variable:

   @UNITTABS = split /:/, $ENV{UNITTAB} unless @UNITTABS;

which means the contents of this environment variable might be misinterpreted on Windows.

**Comment by briandfoy** [comment]
What is the best way to handle the separator issue? use the value of $Config{path_sep}? Or, is it more complicated?

**Comment by nanis** [comment]
Commit  f61af29 should take care of it.

**Comment by briandfoy** [comment]
Fixed by #47.
