### ISSUE TITLE
isprint is not a valid POSIX macro

### ISSUE THREAD

**Issue by eserte** [briandfoy/PerlPowerTools#48]
Starting with perl 5.24.0 it is not possible to use `POSIX::isprint()` anymore. I see one usage of this function in `bin/sort`, and an error can be seen if used like this:
```
$ echo a | perl5.24.0 -Mblib bin/sort -k 1i
isprint is not a valid POSIX macro at (eval 4) line 5
```
In earlier perl versions there was only a deprecation warning:
```
$ echo a | perl5.20.3 -Mblib bin/sort -k 1i
Calling POSIX::isprint() is deprecated at (eval 4) line 4.
a
```

`perldoc POSIX` says:

>     "isprint"
>             This function has been removed as of v5.24. It was very similar
>             to matching against "qr/ ^ [[:print:]]+ $ /x", which you should
>             convert to use instead. See "POSIX Character Classes" in
>             perlrecharclass.

**Comment by briandfoy** [comment]
Fixed in 1.012. Thanks,
