### ISSUE TITLE
Remove Test::Trap dependency

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/PerlPowerTools#49]
In general, there should be no dependencies, even for testing. If we have to work harder, so be it.

**Comment by jonasbn** [comment]
Hi @briandfoy,

By no dependencies, you mean no non-core dependencies?

**Comment by briandfoy** [comment]
Yes, no non-core dependencies. And, non-core should use core as of 5.8 even if it takes a bit more work.

**Comment by briandfoy** [comment]
Just noticed the pull request. Let me get the build working and then I'll get the merge done.

**Comment by briandfoy** [comment]
Everything is building nicely now. Thanks for the work!
