### ISSUE TITLE
Undeclared dependency App::find2perl

### ISSUE THREAD

**Issue by eserte** [briandfoy/PerlPowerTools#62]
If App::find2perl is not installed, then t/find.t fails:
```
Please install App::find2perl before continuing.

#   Failed test 'Found files with -amin: find /var/tmp/cpansmoker-1023/2018111715/ppt-find-JXSnKlRM -type f -amin -50'
#   at t/find.t line 46.
#          got: ''
#     expected: '/var/tmp/cpansmoker-1023/2018111715/ppt-find-JXSnKlRM/a/b/c/20.txt
# /var/tmp/cpansmoker-1023/2018111715/ppt-find-JXSnKlRM/d/40.txt
# '
Please install App::find2perl before continuing.

#   Failed test 'Found files with -mmin: find /var/tmp/cpansmoker-1023/2018111715/ppt-find-JXSnKlRM -type f -mmin +50'
#   at t/find.t line 50.
#          got: ''
#     expected: '/var/tmp/cpansmoker-1023/2018111715/ppt-find-JXSnKlRM/e/f/60.txt
# /var/tmp/cpansmoker-1023/2018111715/ppt-find-JXSnKlRM/g/h/i/80.txt
# '
# Looks like you failed 2 tests of 15.
t/find.t ..... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/15 subtests 
```

**Comment by eserte** [comment]
Well, the problem is slightly different: I see that App::find2perl is correctly declared as a prereq. But there are situations when the module is in `PERL5LIB`, but the script find2perl is not in `PATH`. This usually happens in a test-only or test-all-then-install setup. Not sure how this can be fixed. It would be better if App::find2perl had the real implementation of find2perl, and in this case PPT could use the module instead of the script.

**Comment by eserte** [comment]
Or it could we workarounded by extending `PATH` according to the `PERL5LIB` setting, or the current `@INC`. Something like this (would need adjustment for Windows because of path separators):
```
$ENV{PATH} .= ":" . join(":", map { s{/blib/lib$}{/blib/script}r } grep { m{/blib/lib} } @INC);
```

**Comment by briandfoy** [comment]
The problem was that the find test used `perl` instead of `$^X`, so it was sometimes a different perl.

**Comment by eserte** [comment]
The find2perl related tests still fail on some systems for the latest devel versions of PPT. I did not look thoroughly into the problem but I think it's about test-only-systems or test-all-then-install-systems --- on these systems find2perl is not yet available in the final location, but somewhere in a blib/script directory relative to one of the directories in `@INC`.

**Comment by briandfoy** [comment]
Yeah, I'm still trying to track this down. That sounds helpful.

Maybe I should just distribute find2perl myself.

**Comment by xiaoyafeng** [comment]
Please, adding a force option when installation is really annoying, thanks.

**Comment by briandfoy** [comment]
@xiaoyafeng  - do the current sources still cause problems for you?

**Comment by xiaoyafeng** [comment]
yes, I've tried install PPT 1.016 on windows 2016 yesterday, still failed by App::find2perl issue. sorry I left error messages on the server.

**Comment by mohawk2** [comment]
Perhaps this code would help (https://metacpan.org/source/INGY/Inline-0.86/lib/Inline.pm#L805)? It reconstructs a minimal set of `-I` flags for a new Perl process, intended for the "test-only" etc systems. If so, I should probably extract it into its own module, since it's probably generally useful.

**Comment by mohawk2** [comment]
Having sought counsel on suitable naming, my current intent is bundle that code up, with an additional `grep !ref`, into something called `Devel::RecreateINC` in a few days.

**Comment by briandfoy** [comment]
I haven't heard this complaint in awhile, so I'm closing this. If people still experience this, we can reopen it.
