### ISSUE TITLE
Pager

### ISSUE THREAD

**Issue by belg4mit** [briandfoy/PerlPowerTools#68]
[I have helped put together a less-like pager](https://metacpan.org/release/IO-Pager/source/lib/IO/Pager/tp) that could be PARed into a single file distribution (save for Term::ReadKey's libraries), and have some more user-oriented documentation developed if there's interest. It's not going to be switch compatible or feature complete though. Likewise a more-ish variant could be produced, without the Term::ReadKey dependency even, though at the expense of slightly different behavior for piped content.

**Comment by briandfoy** [comment]
I'm open to this, but the PerlPowerTools constraints are mostly core-only and works on Perl v5.8.

**Comment by briandfoy** [comment]
Since there's been no action, I'm closing this. It's not a rejection of the idea, but merely housekeeping to not have long term open issues.
