### ISSUE TITLE
grep -w mishandles patterns not ending or beginning in a word character

### ISSUE THREAD

**Issue by epa** [briandfoy/PerlPowerTools#69]
For example, you might want to search some source code for calls to `bar()` and pass the `-w` flag so that other functions like `lumbar()` are not matched.

`
% grep -w 'bar[(][)]' source.c
`

(You have to escape the () characters in the regexp of course.)  But although this works fine with GNU `grep -w`, the PPT version of `grep` doesn't find a match:

`
% echo 'bar()' | perl ./bin/grep -w 'bar[(][)]'
`
_(no output)_

This is because currently `-w` works by wrapping the regexp in `\b` anchors.  It's related to https://rt.perl.org/Public/Bug/Display.html?id=127670

If you use the alternative mentioned in that bug, the line of code in `grep` becomes

`$opt{w}   && (@patterns = map {'(?:\b|(?!\w))' . $_ . '(?:\b|(?<!\w))'} @patterns);`

But while this is an improvement, whether it's entirely correct is a matter of opinion.  I think it does not completely match GNU `grep -w`.  Another incantation is to allow either kind of word break: `(?:\b|\b{wb})` before and after.

**Comment by briandfoy** [comment]
Noted. Can you try that and make a pull request?

**Comment by epa** [comment]
I'm also looking into how the `-w` flag is handled in `ack`.  I'll see if I can get a consensus with that project and then send the same thing as a merge request here.

**Comment by briandfoy** [comment]
This is in 1.023. Thanks,
