### ISSUE TITLE
Get rid of indirect object notations

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/PerlPowerTools#73]
Here's a bunch of violations:

https://kritika.io/users/briandfoy/repos/7253941177493998/snapshots/1/violations?rule=Objects::ProhibitIndirectSyntax

It's code that puts the method first (as C++ would):

     $t0 = new Benchmark;

Turn this into the preferred syntax:

    $t0 = Benchmark->new;

That's it.

The affected files. Do as many as you like:

- [x] bin/file
- [x] bin/robots
- [x] bin/look
- [x] bin/ar
- [x] bin/whois
- [x] bin/diff
- [x] bin/time
- [x] bin/mail
- [x] bin/pr
- [x] bin/rev
- [x] bin/tac

https://kritika.io/users/briandfoy/repos/7253941177493998/snapshots/1/files/bin/file?expand=104#L104

**Comment by IvanLudvig** [comment]
I'm going to try to solve this issue
