### ISSUE TITLE
Use lexical loop iterators

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/PerlPowerTools#74]
There are a bunch of `for` and `foreach` loops that don't use lexical loop variables:

https://kritika.io/users/briandfoy/repos/7253941177493998/snapshots/1/violations?limit=20&page=1&rule=Variables%3A%3ARequireLexicalLoopIterators

For example:

    foreach $x ( ... )

Instead, that should be:

    foreach my $x ( ... )

Many of these program are not yet strict safe, but this is a good step to getting closer to that.

Do as many or as few of the problem files as you like. For Hacktoberfest, it doesn't matter how big or complete the pull request is. :)

**Comment by mohawk2** [comment]
This seems to be fixed by the attached PR? Can it be closed?
