### ISSUE TITLE
Modulinos?

### ISSUE THREAD

**Issue by mohawk2** [briandfoy/PerlPowerTools#85]
It seems to me all the PPTs should be modulinos?

**Comment by briandfoy** [comment]
That would complicate things quite a bit. These should be single file things that people can grab individually.

**Comment by mohawk2** [comment]
It seems I don't understand modulinos, then. I thought that described Perl code that could be grabbed individually and just run as a command-line script, but if loaded into another program would make its "main" function instead be callable? The changes required to implement this would mostly involve inserting `package PerlPowerTools::cat_or_whatever; sub main {` and `}` and a `main(@ARGV) unless caller`.

If that understanding were correct, then the various scripts in this distro could also be utilised by e.g. pure-perl-make to avoid calling the shell at all for supported tasks, which would make things much faster, particularly on Windows. Spoiler: I am in fact intending to make pure-perl-make do that. I'd hoped these scripts would make that easy.

Can you help me understand why this would be complicated?

**Comment by briandfoy** [comment]
Ah, I see what you are saying. I guess that could work if someone wanted to do the work. But, the tests still need to check them as scripts.

If you'd like to do that, pick one program and let's try it out.

**Comment by mohawk2** [comment]
Of course you're right that starting with one is a good idea.

My approximate plan will be to start also from using https://metacpan.org/pod/Modulino::Demo, while also probably making a small test framework that makes testing the scripts/modules much easier: I'm thinking of a data-driven approach allowing one to just express fixtures and test-cases, that would run the tests against both the script incarnation and the module incarnation with no extra effort.

**Comment by briandfoy** [comment]
I'm not closing this as a rejection. I've answered the question and if you want to move forward, send a PR. Just don't go crazy with frameworks and such though :)
