### ISSUE TITLE
mkdir -p creates a directory called "-p"

### ISSUE THREAD

**Issue by mohawk2** [briandfoy/PerlPowerTools#87]
That was, to say the least, unexpected.

**Comment by briandfoy** [comment]
I haven't been able to reproduce this. Can you show me how you got it to do this?

**Comment by mohawk2** [comment]
This was on Windows, so on reflection I assume it must have used the builtin instead. Closing.

**Comment by briandfoy** [comment]
For what it's worth, no tools in PerlPowerTools should be using something that doesn't work on Windows.
