### ISSUE TITLE
'units' uses 'unittab' but this file doesn't (always?) exist

### ISSUE THREAD

**Issue by kal247** [briandfoy/PerlPowerTools#99]
This file doesn't exist on Linux (Arch), macOS, Windows :

Couldn't read definitions from from `/usr/lib/unittab': No such file or directory; aborting at ../bin/units line 171.

**Comment by briandfoy** [comment]
There are a few things to do here:

1. Add other paths to the list of default files
2. Tell people where to get units
3. Distribute a default set

This isn't trivial though.

**Comment by hsmyers** [comment]
1. try every path that makes sense
2. if not found, explain (bitch) about missing file with info on where they might find same
3. load minimally useful hard coded version
Roughly what I'd do, at least. Could you expand/explain complications?

**Comment by briandfoy** [comment]
The biggest complication is that the current program doesn't parse modern formats, or some of the formats from the past.

**Comment by hsmyers** [comment]
Could the parse failure be used as a signature?

**Comment by briandfoy** [comment]
I've hardcoded some starter data for know, as well as fixed the missing exponentiation stuff. That should take care of this issue. It will be in the next release.
